version: "3.6"

services:
  uploader:
    # image: mayth/simple-upload-server
    build: .
    ports:
      - "25478:25478"
    command:
      - -token
      - c21beeafd4289e8ff916666666692333
      - -upload_limit
        # 768 MB
      - "805306368"
      - -port
      - "25478"
        # dir in docker to use for uploads/downloads
      - /var/data
    volumes:
      - $HOME/tmp:/var/data
