version: "3.6"

networks:
  file-uploader-network:

services:
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - file-uploader-network
    ports:
      - "8888:80"
  uploader:
    # image: mayth/simple-upload-server
    build: .
    networks:
      - file-uploader-network
    expose:
      - "25478"
    command:
      - -token
      - c21beeafd4289e8ff916666666692333
      - -upload_limit
        # 768 MB
      - "805306368"
      - -port
      - "25478"
        # dir in docker to use for uploads/downloads
      - /var/data
    volumes:
      - $HOME/tmp:/var/data
